import {
  ArrowDownLeft,
  ArrowRight,
  ArrowUpRight,
  BadgeEuro,
  Box,
  Camera,
  Check,
  ChevronDown,
  Clock3,
  Download,
  Factory,
  Globe2,
  Info,
  Layers3,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Network,
  PackageCheck,
  Pencil,
  PhoneCall,
  ScanBarcode,
  Search,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Store,
  TriangleAlert,
  Truck,
  Upload,
  UserRound,
  Warehouse,
  X,
  type LucideIcon,
} from "lucide-react";

import type { IconName } from "@/lib/landing-content";

const ICONS: Record<IconName, LucideIcon> = {
  check: Check,
  x: X,
  arrow: ArrowRight,
  phone: Smartphone,
  camera: Camera,
  ai: Sparkles,
  store: Store,
  price: BadgeEuro,
  box: Box,
  clock: Clock3,
  euro: BadgeEuro,
  export: ArrowUpRight,
  import: ArrowDownLeft,
  truck: Truck,
  distribution: Network,
  delivery: PackageCheck,
  warehouse: Warehouse,
  globe: Globe2,
  user: UserRound,
  factory: Factory,
  pin: MapPin,
  layers: Layers3,
  edit: Pencil,
  publish: Upload,
  upload: Upload,
  barcode: ScanBarcode,
  shield: ShieldCheck,
  download: Download,
  chevron: ChevronDown,
  menu: Menu,
  info: Info,
  search: Search,
  warn: TriangleAlert,
  mail: Mail,
  phoneCall: PhoneCall,
  whatsapp: MessageCircle,
};

export function Ic({ name }: { name: IconName }) {
  const Icon = ICONS[name];
  return <Icon aria-hidden="true" strokeWidth={1.9} />;
}
